### ISSUE TITLE
`build_hurdle_3_trusty.sh` fails to install numpy

### ISSUE THREAD

**Issue by mainland** [SpectrumCollaborationChallenge/phase1-hurdles#18] opened 2016-11-04 17:17 UTC
The `build_hurdle_3_trusty.sh` script uses pip to install jupyter, numpy, and matplotlib, but this fails because the necessary prerequisites for matplotlib are not installed, leading to numpy not being installed. The resulting container therefore cannot run the examples.

The solution is to add the following packages to those installed using apt: `libpng-dev` `libfreetype6-dev` `libxft-dev`

**Comment by itsb** [comment] 2016-11-07 03:49
I ran into the same issue when I was creating a docker image based on that script.
libxft-dev is sufficient as it brings in libpng12-dev and libfreetype6-dev.
`apt-get install libxft-dev`

**Comment by craig-pomeroy** [comment] 2016-11-08 16:17
To try to reproduce this issue, we've run the build_hurdle_3_trusty.sh script at rev 2843cef in fresh installs of Ubuntu VMs. We've also tested the build script after shutting down any running hurdle 3 LXC containers and completely clearing out the ./lxc subdirectory in hurdle3. 

We have not been able to reproduce this issue.

**Comment by itsb** [comment] 2016-11-08 18:34
You're right. I am also unable to reproduce the issue right now. Sorry for the false alarm. I see only a few patch version differences between my image from a few days ago and today, e.g., pip 9.0.0 versus 9.0.1. Perhaps some PyPI mirror was down/misbehaving over the weekend. Currently behind a corporate firewall/proxy, will confirm the non-issue tonight from home.

**Comment by itsb** [comment] 2016-11-09 06:51
Confirmed false alarm.

**Comment by craig-pomeroy** [comment] 2016-11-09 15:15
Closing for now. Will reopen if the issue crops back up for other users.

**Closed by craig-pomeroy** 2016-11-09 15:15 UTC
