### ISSUE TITLE
hurdle 3: same seed is used for all trials

### ISSUE THREAD

**Issue by mmaroti** [SpectrumCollaborationChallenge/phase1-hurdles#15] opened 2016-11-03 14:46 UTC
If the seed is set to None, then it will be replaced by a random one but will be reused for all trials. Looking at the results.json we see that all 10 trials indeed used the same seed and initial state.

**Comment by craig-pomeroy** [comment] 2016-11-03 15:27
closing as a duplicate of #14

**Closed by craig-pomeroy** 2016-11-03 15:27 UTC
