### ISSUE TITLE
Compressing containers

### ISSUE THREAD

**Issue by ilhaan** [SpectrumCollaborationChallenge/phase1-hurdles#33] opened 2016-11-22 01:33 UTC
I am compressing solution containers for submission and ran the following: 
```
sudo tar cjf hurdle1_solution.tar.bz2 -C lxc/ metadata.yaml -C hurdle1_solution_trusty_lxc rootfs
```
I get an error message: `tar: metadata.yaml: Cannot stat: No such file or directory`. 

Not sure what I'm doing wrong here.

**Comment by volgy** [comment] 2016-11-22 02:37
It seems, your container has been built before the SC2 team has switched over to LXD. You can create the missing lxc/metadata.yaml (assuming the current folder is hurdle1):

```
$ echo architecture: "amd64" > lxc/metadata.yaml
$ echo creation_date: `date +%s` >> lxc/metadata.yaml
```

You also need to check, if the container has been built with the expected id mapping:

```
$ ls lxc/hurdle1_solution_trusty_lxc/rootfs
```

should look something like this:

```
drwxr-xr-x  2 165536 165536 4096 Nov  2 22:58 bin
drwxr-xr-x  2 165536 165536 4096 Apr 10  2014 boot
drwxr-xr-x  3 165536 165536 4096 Nov  2 22:57 dev
drwxr-xr-x 78 165536 165536 4096 Nov 20 10:43 etc
drwxr-xr-x  5 165536 165536 4096 Nov  8 16:16 home
drwxr-xr-x 12 165536 165536 4096 Nov  8 15:08 lib
drwxr-xr-x  2 165536 165536 4096 Nov  2 22:58 lib64
drwxr-xr-x  2 165536 165536 4096 Nov  2 22:56 media
drwxr-xr-x  2 165536 165536 4096 Apr 10  2014 mnt
drwxr-xr-x  2 165536 165536 4096 Nov  2 22:56 opt
drwxr-xr-x  2 165536 165536 4096 Apr 10  2014 proc
drwx------  2 165536 165536 4096 Nov  2 22:56 root
drwxr-xr-x  8 165536 165536 4096 Nov  8 15:06 run
drwxr-xr-x  2 165536 165536 4096 Nov  2 22:58 sbin
drwxr-xr-x  2 165536 165536 4096 Nov  2 22:56 srv
drwxr-xr-x  2 165536 165536 4096 Mar 12  2014 sys
drwxrwxrwt  4 165536 165536 4096 Nov 20 10:42 tmp
drwxr-xr-x 10 165536 165536 4096 Nov  2 22:56 usr
drwxr-xr-x 11 165536 165536 4096 Nov  2 22:56 var
```

If the owner uid is not **165536**, you might be better off rebuilding the container with the latest version of the script.

**Comment by MihailSichitiu** [comment] 2016-11-22 02:59
If the creation date is not important (which it clearly isn't as you're suggesting to create it with the current time), why is it needed at all?

And the scripts for building the containers from scratch do not work on the same computer twice. At least not in a different directory to avoid destroying the existing ones which conceivably hold the original ones.

Finally, the S3 Darpa containers do not start.

**Comment by ilhaan** [comment] 2016-11-22 04:37
I created the `metadata.yaml` file and I was able to compress it without error. However, after moving this container to a new machine, I can't ssh into it. I get the following: 
```
Connection reset by 10.186.113.80 port 22
```
@volgy I built this container today, after setting up and successfully using LXD with the other hurdles. I also made sure I pulled the latest commits before building.

**Comment by craig-pomeroy** [comment] 2016-11-22 05:31
It appears that a recent build of the Ubuntu Trusty template at https://us.images.linuxcontainers.org/ is causing issues with the build scripts. We'll be posting a cached version of a previous version of the Trusty template on our S3 bucket shortly and providing instructions on how to incorporate it. 

@ilhaan: This may or may not be impacting you, depending on how old your cached LXC image is. 

The LXC cache is located at ~/.cache/lxc. The build scripts use the download template. If you have a cached version of this template, you can check its build ID if you run: 

`cat ~/.cache/lxc/download/ubuntu/trusty/amd64/default/build_id`

The build_id of the cached image we've successfully tested is 20161114_03:49. If you have something more recent than that, it could be part of your issues. Otherwise, you should verify that the numeric user ids in your container start off at 165536. 
 
One other question for debugging: do the scoring containers from the DARPA S3 bucket work on both of your test machines?

**Comment by sodium24** [comment] 2016-11-22 05:34
If you have the steps or a script for rebuilding your container, it may be worth fully deleting the lxc directory after making a backup ("rm -rf lxc"). And make sure your build_*.sh script is up to date with the newest version in the repo, if you've made any modifications to it. The newest version in the repo has some lines near the end which should be generating the metadata.yaml file automatically

**Comment by ilhaan** [comment] 2016-11-22 06:08
Just checked, the owner uid is not 165536. I used the latest build scripts to build the containers (made sure to `git pull` before building). 

@craig-pomeroy: The build_id of my cached image is `20161103_03:49`. Also, the scoring containers from the DARPA S3 bucket do work without issues on both my machines.

**Comment by craig-pomeroy** [comment] 2016-11-22 06:17
@ilhaan it sounds like the issue is in the subgid and subuid mappings. 

Check /etc/subgid and /etc/subuid. We'd recommend having all of your users share the same range, starting at 165536. Also confirm this matches what you have in ~/.config/lxc/default.conf on both machines.

**Comment by ilhaan** [comment] 2016-11-22 06:31
@craig-pomeroy Looks like that is my issue. I didn't realize that with the change to LXD I had to make changes to my LXC settings as well. I only followed the instructions under **Update user groups to be able to use LXD** after the switch to LXD last week. My current LXC settings are from before the Nov 15th updates.

**Comment by craig-pomeroy** [comment] 2016-11-22 06:35
Let us know once you've tested a container if that resolves your issue. I'll keep this open until then.

**Comment by ilhaan** [comment] 2016-11-22 13:23
I rebuilt the containers for hurdles 1 & 2 after updating my LXC and LXD configs (subgid and subuid etc.) I verified that `ls -n lxc/hurdle1_solution_trusty_lxc/rootfs` shows the owner uid 165536. 

Also, the build_id of my cached image is still `20161103_03:49`. 

These new containers seem to have some GNURadio issue. When I try to run the solution stub in hurdle2 for example, I get this: 
```
Traceback (most recent call last):
  File "./hurdle2_solution_stub_edited.py", line 9, in <module>
    from gnuradio import blocks
ImportError: No module named gnuradio
```
I did not have any issues with GNURadio before this build. Do I need to add some path to my environment to fix this?

**Comment by MihailSichitiu** [comment] 2016-11-22 15:10
I can confirm too that the cache trick does not solve the gnuradio problem: the rebuilt containers fail with or without the cache trick.

**Comment by volgy** [comment] 2016-11-22 15:23
See my comment on #35 w.r.t the gnuradio build issue.

**Comment by MihailSichitiu** [comment] 2016-11-23 03:51
After swig all builds correctly and smoothly. Thank you very much for the help!

**Comment by craig-pomeroy** [comment] 2016-11-28 20:18
Marking as closed

**Closed by craig-pomeroy** 2016-11-28 20:18 UTC
